-- Product catalog. The backend is the source of truth for which products are
-- publicly visible on the portal; the public API returns only rows that are
-- enabled AND visibility = 'PUBLIC', ordered by display_order.
CREATE TABLE products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stable external identifier. NEVER the display name — code and the admin
    -- API key off this, so it must not change once shipped.
    product_key       VARCHAR(64)  NOT NULL UNIQUE,
    name              VARCHAR(128) NOT NULL,
    tagline           VARCHAR(256),
    description       TEXT,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    -- PUBLIC  = eligible for the public portal (still gated by `enabled`)
    -- HIDDEN  = never returned by the public API regardless of `enabled`
    visibility        VARCHAR(16)  NOT NULL DEFAULT 'PUBLIC'
                        CONSTRAINT products_visibility_chk CHECK (visibility IN ('PUBLIC', 'HIDDEN')),
    product_type      VARCHAR(32)  NOT NULL
                        CONSTRAINT products_type_chk CHECK (product_type IN ('QUDOSSL_EDITION', 'PROVIDER', 'LIBRARY')),
    -- Distinguishes the two QudoSSL editions; NULL for non-QudoSSL products.
    edition           VARCHAR(16)
                        CONSTRAINT products_edition_chk CHECK (edition IS NULL OR edition IN ('COMMUNITY', 'COMMERCIAL')),
    documentation_url VARCHAR(512),
    repository_url     VARCHAR(512),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- The public-list query filters on (enabled, visibility) and orders by display_order.
CREATE INDEX idx_products_public ON products (visibility, enabled, display_order);
