-- Lightweight audit trail for product-configuration changes. One row is written
-- per changed field on every admin mutation, recording who changed what, from
-- what, to what, and when. Product visibility is operational configuration, so
-- these changes are worth an immutable record.
CREATE TABLE product_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_key    VARCHAR(64)  NOT NULL,
    admin_username VARCHAR(128) NOT NULL,
    field_changed  VARCHAR(64)  NOT NULL,
    old_value      VARCHAR(512),
    new_value      VARCHAR(512),
    changed_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Audit reads are "recent entries for this product", newest first.
CREATE INDEX idx_product_audit_product ON product_audit (product_key, changed_at DESC);
