-- Commercial support pricing tiers. The three tiers come from the QudoSSL
-- Commercial product overview. Prices are PROPOSED and change over time, so they
-- live in the database and are edited through the Admin Portal rather than
-- hard-coded in the frontend — the backend stays the source of truth for what
-- the public site shows.
--
--   price_visible = TRUE  -> the public API returns the amount (site shows "$X/yr")
--   price_visible = FALSE -> the amount is withheld (site shows "Contact sales")
-- The amount is always retained so toggling visibility never loses the figure.
CREATE TABLE pricing_tiers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stable external identifier; the admin API keys off this, never the name.
    tier_key      VARCHAR(64)  NOT NULL UNIQUE,
    name          VARCHAR(128) NOT NULL,
    audience      VARCHAR(512),
    -- Annual price in the currency's major unit (whole dollars). NULL = unset.
    price_amount  BIGINT
                    CONSTRAINT pricing_tiers_amount_chk CHECK (price_amount IS NULL OR price_amount >= 0),
    currency      VARCHAR(3)   NOT NULL DEFAULT 'USD',
    price_visible BOOLEAN      NOT NULL DEFAULT TRUE,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    highlighted   BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_pricing_tiers_public ON pricing_tiers (enabled, display_order);

-- Seed the three proposed tiers (amounts from the Commercial product overview).
INSERT INTO pricing_tiers
    (tier_key, name, audience, price_amount, currency, price_visible, enabled, highlighted, display_order)
VALUES
    ('basic', 'Basic',
     'Development teams and production applications in small and mid-size enterprises',
     25000, 'USD', TRUE, TRUE, FALSE, 1),
    ('engineering', 'Engineering',
     'Regulated and large enterprises running QudoSSL in production',
     65000, 'USD', TRUE, TRUE, TRUE, 2),
    ('enterprise', 'Enterprise',
     'Banks, financial institutions and critical infrastructure where cryptographic downtime is a material business event',
     175000, 'USD', TRUE, TRUE, FALSE, 3)
ON CONFLICT (tier_key) DO NOTHING;
