-- Admin-managed white papers / resources. Submitted through Qudo Admin and shown
-- on the public Resources → White papers page. The backend is the source of truth
-- for which are visible (published), consistent with products and pricing.
--
-- document_url is a link the admin provides (a hosted PDF, or an on-site page).
-- File upload can be layered on later; a URL keeps the first version simple.
CREATE TABLE white_papers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(256)  NOT NULL,
    description   TEXT,
    category      VARCHAR(64),
    document_url  VARCHAR(1024) NOT NULL,
    published     BOOLEAN       NOT NULL DEFAULT TRUE,
    display_order INTEGER       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_white_papers_public ON white_papers (published, display_order);

-- Seed one safe example pointing at an existing public page, so the feature is
-- demonstrable on first load. Admins add their own (PDF links, etc.) from Qudo Admin.
INSERT INTO white_papers (title, description, category, document_url, published, display_order)
VALUES
    ('QudoSSL Benchmark Report',
     'TLS 1.3 handshake throughput and ML-KEM / ML-DSA operation rates for QudoSSL across macOS, Linux and Windows, measured on the OpenSSL FIPS provider.',
     'Performance', '/benchmark', TRUE, 1);
